language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head

script:
  - bundle exec rspec spec

before_script:
  - psql -c 'create database pg_lock_test;' -U postgres

addons:
  postgresql: "9.3"

matrix:
  allow_failures:
    - rvm: ruby-head
