language: ruby
services:
  - postgresql
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

script:
  - bundle exec rspec spec

before_install:
  - gem install bundler

before_script:
  - psql -c 'create database pg_lock_test;' -U postgres

matrix:
  allow_failures:
    - rvm: ruby-head
